name: Releases
on:
    push:
        branches:
            - 'master'
        tags:
            - 'v*'

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Automatic Releases
              uses: marvinpinto/action-automatic-releases@v1.2.1
              with:
                  repo_token: '${{ secrets.GITHUB_TOKEN }}'
                  prerelease: false
